ALTER TABLE `cervesium`.`usuarios` 
CHANGE COLUMN `nombre` `usuario` VARCHAR(15) NULL ,
ADD COLUMN `nombre` VARCHAR(20) NULL DEFAULT NULL ,
ADD COLUMN `apellido` VARCHAR(20) NULL DEFAULT NULL AFTER `nombre`,
ADD COLUMN `valido` TINYINT NOT NULL DEFAULT 0 AFTER `tipo`;
